replicaCount: 1

image:
  repository: "${DOCKER_HUB_USERNAME}/inventory-service"
  tag: latest
  pullPolicy: Always

service:
  type: NodePort
  port: 8080
  nodePort: 30002

containerPort: 8006

hpa:
  enabled: true
  minReplicas: 3
  maxReplicas: 10
  targetCPUUtilizationPercentage: 70
